/*
 *  BACA DENGAN TELITI !!!
 * 
 *  Anda boleh menggunakan, mengubah, menghapus, menambah, dan
 *  melakukan hal yang anda inginkan ke dalam source code ini.
 * 
 *  Dan saya tidak bertanggung jawab atas kesalahan,
 *  bug, atau keanehan yang ada dalam source code ini, dan
 *  saya juga TIDAK MENERIMA PERTANYAAN dari Anda
 *  mengenai isi source code ini.
 * 
 *  Semoga source code ini bermanfaat bagi Anda, dan juga
 *  bermanfaat bagi project yang sedang Anda buat.
 * 
 *  Salam saya, Eko Kurniawan Khannedy
 */

/*
 * GlassPaneLoading.java
 *
 * Created on 04 Feb 09, 13:31:41
 */
package glasspaneloader;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author echo
 */
public class ConfirmGlassPaneLoader extends javax.swing.JPanel implements ActionListener {

    private Color colorTranparan;

    /**
     * Creates new form GlassPaneLoading
     */
    public ConfirmGlassPaneLoader() {
        colorTranparan = new Color(255, 255, 255, 175);
        initComponents();

        addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
            }
        });
        addMouseMotionListener(new MouseAdapter() {
        });
        addMouseWheelListener(new MouseAdapter() {
        });
        addKeyListener(new KeyAdapter() {
        });
    }

    @Override
    protected void paintComponent(Graphics g) {

        Graphics2D gd = (Graphics2D) g.create();

        gd.setColor(colorTranparan);
        gd.fillRect(0, 0, getWidth(), getHeight());

        gd.dispose();

        super.paintComponent(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        txtconfirmUserName = new JTextField();
        jLabel1 = new JLabel();
        txtconfirmPassword = new JPasswordField();
        btConfirm = new JButton();
        btcancel = new JButton();

        setOpaque(false);
        setPreferredSize(new Dimension(600, 240));
        setLayout(new AbsoluteLayout());

        jLabel2.setFont(new Font("Tahoma", 1, 14));         jLabel2.setText("Do you want to change configuration setting ?");
        add(jLabel2, new AbsoluteConstraints(370, 217, -1, 20));

        jLabel3.setFont(new Font("Tahoma", 1, 14));         jLabel3.setForeground(new Color(255, 0, 51));
        jLabel3.setText("please confrm it.");
        add(jLabel3, new AbsoluteConstraints(460, 247, -1, 20));

        jLabel4.setFont(new Font("Tahoma", 0, 14));         jLabel4.setText("User Name");
        add(jLabel4, new AbsoluteConstraints(300, 295, 140, 30));

        txtconfirmUserName.addActionListener(this);
        add(txtconfirmUserName, new AbsoluteConstraints(480, 290, 240, 30));

        jLabel1.setFont(new Font("Tahoma", 0, 14));         jLabel1.setText("Password");
        add(jLabel1, new AbsoluteConstraints(300, 345, 140, 30));
        add(txtconfirmPassword, new AbsoluteConstraints(480, 340, 240, 30));

        btConfirm.setFont(new Font("Tahoma", 1, 12));         btConfirm.setText("Confirm");
        btConfirm.addActionListener(this);
        add(btConfirm, new AbsoluteConstraints(560, 430, 120, 30));

        btcancel.setFont(new Font("Tahoma", 1, 12));         btcancel.setText("Cancel");
        btcancel.addActionListener(this);
        add(btcancel, new AbsoluteConstraints(690, 430, 120, 30));
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(ActionEvent evt) {
        if (evt.getSource() == txtconfirmUserName) {
            ConfirmGlassPaneLoader.this.txtconfirmUserNameActionPerformed(evt);
        }
        else if (evt.getSource() == btConfirm) {
            ConfirmGlassPaneLoader.this.btConfirmActionPerformed(evt);
        }
        else if (evt.getSource() == btcancel) {
            ConfirmGlassPaneLoader.this.btcancelActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void txtconfirmUserNameActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtconfirmUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfirmUserNameActionPerformed

    private void btConfirmActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConfirmActionPerformed

    private void btcancelActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btcancelActionPerformed
        System.out.println(ConfirmGlassPaneLoader.this.getParent().getName()+" ssssssssss");
        ConfirmGlassPaneLoader.this.setVisible(false);
    }//GEN-LAST:event_btcancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected JButton btConfirm;
    protected JButton btcancel;
    protected JLabel jLabel1;
    protected JLabel jLabel2;
    protected JLabel jLabel3;
    protected JLabel jLabel4;
    protected JPasswordField txtconfirmPassword;
    protected JTextField txtconfirmUserName;
    // End of variables declaration//GEN-END:variables
}
