/*
 *  BACA DENGAN TELITI !!!
 * 
 *  Anda boleh menggunakan, mengubah, menghapus, menambah, dan
 *  melakukan hal yang anda inginkan ke dalam source code ini.
 * 
 *  Dan saya tidak bertanggung jawab atas kesalahan,
 *  bug, atau keanehan yang ada dalam source code ini, dan
 *  saya juga TIDAK MENERIMA PERTANYAAN dari Anda
 *  mengenai isi source code ini.
 * 
 *  Semoga source code ini bermanfaat bagi Anda, dan juga
 *  bermanfaat bagi project yang sedang Anda buat.
 * 
 *  Salam saya, Eko Kurniawan Khannedy
 */

/*
 * GlassPaneLoading.java
 *
 * Created on 04 Feb 09, 13:31:41
 */
package glasspaneloader;

import java.awt.*;
import java.awt.event.*;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author echo
 */
public class WinGlassPaneLoader extends javax.swing.JPanel {

    private Color colorTranparan;

    /**
     * Creates new form GlassPaneLoading
     */
    public WinGlassPaneLoader() {
        colorTranparan = new Color(255, 255, 255, 175);
        initComponents();

        addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
            }
        });
        addMouseMotionListener(new MouseAdapter() {
        });
        addMouseWheelListener(new MouseAdapter() {
        });
        addKeyListener(new KeyAdapter() {
        });
    }

    @Override
    protected void paintComponent(Graphics g) {

        Graphics2D gd = (Graphics2D) g.create();

        gd.setColor(colorTranparan);
        gd.fillRect(0, 0, getWidth(), getHeight());

        gd.dispose();

        super.paintComponent(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        btNewGame = new JButton();

        setBorder(BorderFactory.createMatteBorder(1, 1, 300, 300, new ImageIcon(getClass().getResource("/images/view/glass default 3.png")))); // NOI18N
        setOpaque(false);
        setPreferredSize(new Dimension(300, 300));
        setLayout(new AbsoluteLayout());

        jLabel1.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new Color(255, 255, 255));
        add(jLabel1, new AbsoluteConstraints(60, 130, 190, 50));

        btNewGame.setText("New Game");
        add(btNewGame, new AbsoluteConstraints(100, 220, 100, 30));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected JButton btNewGame;
    protected JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public void setLabel(String name){
        jLabel1.setText(name);
    }

}
