/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import tictactoe.control.TicTacToeController;
import tictactoe.user.ComputerPlayer;

/**
 *
 * @author Amila
 */
public class PlayBoard extends javax.swing.JPanel {
    
    PlayView playView;
    JPanel pan;
    String player1;
    String player2;

    ImageIcon player1Icon = new ImageIcon(getClass().getResource("/images/gametool/X mark.PNG"));
    ImageIcon player2Icon = new ImageIcon(getClass().getResource("/images/gametool/O mark.PNG"));
    int[][] table = new int[3][3];
    JLabel[][] labels = new JLabel[3][3];
    ComputerPlayer computerPlayer = new ComputerPlayer();
    int play=1;
    /**
     * Creates new form PlayBoard
     */
    public PlayBoard() {
        initComponents();
    }
    
    public PlayBoard(PlayView playView,JPanel pan,String player1,String player2) {
        initComponents();
        winGlassPaneLoader2.setVisible(false);
        this.playView=playView;
        this.pan=pan;
        this.player1=player1;
        this.player2=player2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        winGlassPaneLoader2 = new glasspaneloader.WinGlassPaneLoader();
        lb00 = new javax.swing.JLabel();
        lb22 = new javax.swing.JLabel();
        lb01 = new javax.swing.JLabel();
        lb02 = new javax.swing.JLabel();
        lb10 = new javax.swing.JLabel();
        lb11 = new javax.swing.JLabel();
        lb12 = new javax.swing.JLabel();
        lb20 = new javax.swing.JLabel();
        lb21 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 300, 300, new javax.swing.ImageIcon(getClass().getResource("/images/unnamed.png")))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(winGlassPaneLoader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lb00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb00MouseClicked(evt);
            }
        });
        labels[0][0]=lb00;
        jPanel1.add(lb00, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 90));

        lb22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb22MouseClicked(evt);
            }
        });
        labels[2][2]=lb22;
        jPanel1.add(lb22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 90, 90));

        lb01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb01MouseClicked(evt);
            }
        });
        labels[0][1]=lb01;
        jPanel1.add(lb01, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, 90));

        lb02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb02MouseClicked(evt);
            }
        });
        labels[0][2]=lb02;
        jPanel1.add(lb02, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 90, 90));

        lb10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb10MouseClicked(evt);
            }
        });
        labels[1][0]=lb10;
        jPanel1.add(lb10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 90));

        lb11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb11MouseClicked(evt);
            }
        });
        labels[1][1]=lb11;
        jPanel1.add(lb11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 90, 90));

        lb12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb12MouseClicked(evt);
            }
        });
        labels[1][2]=lb12;
        jPanel1.add(lb12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 90, 90));

        lb20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb20MouseClicked(evt);
            }
        });
        labels[2][0]=lb20;
        jPanel1.add(lb20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, 90));

        lb21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb21MouseClicked(evt);
            }
        });
        labels[2][1]=lb21;
        jPanel1.add(lb21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 90, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lb00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb00MouseClicked
        play(0, 0);
    }//GEN-LAST:event_lb00MouseClicked

    private void lb22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb22MouseClicked
        play(2, 2);
    }//GEN-LAST:event_lb22MouseClicked

    private void lb01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb01MouseClicked
        play(0, 1);
    }//GEN-LAST:event_lb01MouseClicked

    private void lb02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb02MouseClicked
        play(0, 2);
    }//GEN-LAST:event_lb02MouseClicked

    private void lb10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb10MouseClicked
        play(1, 0);
    }//GEN-LAST:event_lb10MouseClicked

    private void lb11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb11MouseClicked
        play(1, 1);
    }//GEN-LAST:event_lb11MouseClicked

    private void lb12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb12MouseClicked
        play(1, 2);
    }//GEN-LAST:event_lb12MouseClicked

    private void lb20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb20MouseClicked
        play(2, 0);
    }//GEN-LAST:event_lb20MouseClicked

    private void lb21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb21MouseClicked
        play(2, 1);
    }//GEN-LAST:event_lb21MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb00;
    private javax.swing.JLabel lb01;
    private javax.swing.JLabel lb02;
    private javax.swing.JLabel lb10;
    private javax.swing.JLabel lb11;
    private javax.swing.JLabel lb12;
    private javax.swing.JLabel lb20;
    private javax.swing.JLabel lb21;
    private javax.swing.JLabel lb22;
    private glasspaneloader.WinGlassPaneLoader winGlassPaneLoader2;
    // End of variables declaration//GEN-END:variables
private void play(int row, int column) {
        if(table[row][column] != 1 && table[row][column] != 2){
            if(play==1){
                table[row][column] = 1;
                play=2;
                if(player2.equals("computer")){
                    table = computerPlayer.play(table, 1);
                    play=1;
                }
            }else{
                table[row][column] = 2;
                play=1;
            }
        }
       setView();
    }

    private void setView() {
        for (int i = 0; i < table.length; i++) {
            for (int j = 0; j < table[i].length; j++) {
                if (table[i][j] == 1) {
                    labels[i][j].setIcon(player1Icon);
                } else if (table[i][j] == 2) {
                    labels[i][j].setIcon(player2Icon);
                }
            }
        }
        int[] i = {1, 2};
        decision(TicTacToeController.judgeTicTagToe(table, i));
    }

    private void decision(int p1val) {
        System.out.println(p1val);
        if (p1val == 11) {
            System.out.println("Win" + 1);
            winGlassPaneLoader2.setLabel(player1+" Winning");
            winGlassPaneLoader2.setVisible(true);
        } else if (p1val == 12) {
            System.out.println("Win" + 2);
            winGlassPaneLoader2.setLabel(player2+" Winning");
            winGlassPaneLoader2.setVisible(true);
        }else{
            boolean draw=true;
            L1: for (int i = 0; i < table.length; i++) {
                for (int j = 0; j < table.length; j++) {
                    if(table[i][j]==0){
                        draw=false;
                        System.out.println("aaa "+i+"  "+j);
                        break L1;
                    }
                }
            }
            if(draw){
                winGlassPaneLoader2.setLabel("   Draw.....");
                winGlassPaneLoader2.setVisible(true);
            }
        }
    }

}
