package view;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import tictactoe.control.TicTacToeController;
import tictactoe.user.ComputerPlayer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Amila
 */
public class TicTacToeView extends javax.swing.JFrame {

    ImageIcon player1Icon = new ImageIcon(getClass().getResource("/images/gametool/Cross2.PNG"));
    ImageIcon player2Icon = new ImageIcon(getClass().getResource("/images/gametool/O_mark.PNG"));
    int[][] table = new int[3][3];
    JLabel[][] labels = new JLabel[3][3];
    ComputerPlayer computerPlayer = new ComputerPlayer();

    /**
     * Creates new form TicTacToeView
     */
    public TicTacToeView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb00 = new javax.swing.JLabel();
        lb22 = new javax.swing.JLabel();
        lb01 = new javax.swing.JLabel();
        lb02 = new javax.swing.JLabel();
        lb10 = new javax.swing.JLabel();
        lb11 = new javax.swing.JLabel();
        lb12 = new javax.swing.JLabel();
        lb20 = new javax.swing.JLabel();
        lb21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 300, 300, new javax.swing.ImageIcon(getClass().getResource("/images/unnamed.png")))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb00MouseClicked(evt);
            }
        });
        labels[0][0]=lb00;
        jPanel1.add(lb00, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 90));

        lb22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb22MouseClicked(evt);
            }
        });
        labels[2][2]=lb22;
        jPanel1.add(lb22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 90, 90));

        lb01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb01MouseClicked(evt);
            }
        });
        labels[0][1]=lb01;
        jPanel1.add(lb01, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 90, 90));

        lb02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb02MouseClicked(evt);
            }
        });
        labels[0][2]=lb02;
        jPanel1.add(lb02, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 90, 90));

        lb10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb10MouseClicked(evt);
            }
        });
        labels[1][0]=lb10;
        jPanel1.add(lb10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 90, 90));

        lb11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb11MouseClicked(evt);
            }
        });
        labels[1][1]=lb11;
        jPanel1.add(lb11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 90, 90));

        lb12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb12MouseClicked(evt);
            }
        });
        labels[1][2]=lb12;
        jPanel1.add(lb12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 90, 90));

        lb20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb20MouseClicked(evt);
            }
        });
        labels[2][0]=lb20;
        jPanel1.add(lb20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 90, 90));

        lb21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb21MouseClicked(evt);
            }
        });
        labels[2][1]=lb21;
        jPanel1.add(lb21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 90, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb00MouseClicked
        play(0, 0);
    }//GEN-LAST:event_lb00MouseClicked

    private void lb22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb22MouseClicked
        play(2, 2);
    }//GEN-LAST:event_lb22MouseClicked

    private void lb01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb01MouseClicked
        play(0, 1);
    }//GEN-LAST:event_lb01MouseClicked

    private void lb02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb02MouseClicked
        play(0, 2);
    }//GEN-LAST:event_lb02MouseClicked

    private void lb10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb10MouseClicked
        play(1, 0);
    }//GEN-LAST:event_lb10MouseClicked

    private void lb11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb11MouseClicked
        play(1, 1);
    }//GEN-LAST:event_lb11MouseClicked

    private void lb12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb12MouseClicked
        play(1, 2);
    }//GEN-LAST:event_lb12MouseClicked

    private void lb20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb20MouseClicked
        play(2, 0);
    }//GEN-LAST:event_lb20MouseClicked

    private void lb21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb21MouseClicked
        play(2, 1);
    }//GEN-LAST:event_lb21MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb00;
    private javax.swing.JLabel lb01;
    private javax.swing.JLabel lb02;
    private javax.swing.JLabel lb10;
    private javax.swing.JLabel lb11;
    private javax.swing.JLabel lb12;
    private javax.swing.JLabel lb20;
    private javax.swing.JLabel lb21;
    private javax.swing.JLabel lb22;
    // End of variables declaration//GEN-END:variables

    private void play(int row, int column) {
        if(table[row][column] != 1 && table[row][column] != 2){
            table[row][column] = 1;
            table = computerPlayer.play(table, 1);
        }
       setView();
    }

    private void setView() {
        for (int i = 0; i < table.length; i++) {
            for (int j = 0; j < table[i].length; j++) {
                if (table[i][j] == 1) {
                    labels[i][j].setIcon(player1Icon);
                } else if (table[i][j] == 2) {
                    labels[i][j].setIcon(player2Icon);
                }
            }
        }
        int[] i = {1, 2};
        decision(TicTacToeController.judgeTicTagToe(table, i));
    }

    private void decision(int p1val) {
        System.out.println(p1val);
        if (p1val == 11) {
            System.out.println("Win" + 1);
        } else if (p1val == 12) {
            System.out.println("Win" + 2);
        }
    }
}
